//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.06 at 05:14:26 PM EST 
//


package zikzakjack.hrscott;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the zikzakjack.hrscott package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: zikzakjack.hrscott
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetRegionDetailsResponse }
     * 
     */
    public GetRegionDetailsResponse createGetRegionDetailsResponse() {
        return new GetRegionDetailsResponse();
    }

    /**
     * Create an instance of {@link RegionDetails }
     * 
     */
    public RegionDetails createRegionDetails() {
        return new RegionDetails();
    }

    /**
     * Create an instance of {@link GetRegionDetailsRequest }
     * 
     */
    public GetRegionDetailsRequest createGetRegionDetailsRequest() {
        return new GetRegionDetailsRequest();
    }

}
