//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.06 at 05:14:26 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://zikzakjack/hrscott", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package zikzakjack.hrscott;
